//=============================================================================
// PLAYER3.H - Public API for Player3 Music Player
//=============================================================================
// This is the main header file for the player3 music player. Include this
// file in your application code to use the player.
//
// USAGE EXAMPLE:
//
//   #include "player3.h"
//
//   // Music data (in ROM, generated by gt2reloc)
//   extern const MusicData my_song;
//
//   // Player state (in RAM)
//   static Player player;
//
//   void init_music(void) {
//       player_init(&player, &my_song, 0);  // Initialize with song 0
//   }
//
//   void music_irq(void) {
//       player_play(&player, &my_song);     // Call every frame (50Hz/60Hz)
//   }
//
//=============================================================================

#ifndef PLAYER3_H
#define PLAYER3_H

#include <stdint.h>
#include <stdbool.h>
#include "player3_types.h"
#include "sid.h"

//=============================================================================
// PLAYER API
//=============================================================================

/**
 * Initialize the player with a song.
 *
 * This function prepares the player to play the specified song. It sets up
 * the initialization state, which will be completed on the next call to
 * player_play(). This deferred initialization allows the player to smoothly
 * transition to a new song during playback.
 *
 * INITIALIZATION PROCESS:
 * 1. Call player_init() to mark the song for initialization
 * 2. On next player_play() call, initialization completes:
 *    - All channel state is reset to zero
 *    - SID filter is reset
 *    - Each channel is initialized with default tempo
 *    - Order lists are positioned at start
 *    - Waveforms are loaded
 *
 * @param player Pointer to player state structure (must remain valid)
 * @param music Pointer to music data (must remain valid and in scope)
 * @param song_num Song number to play (0-based)
 *
 * NOTES:
 * - For single-song files, always pass song_num = 0
 * - For multi-song files, song_num can be 0 to MAX_SONGS-1
 * - The music pointer must point to const data (typically in ROM)
 * - The player pointer must point to RAM (for runtime state)
 * - After calling, you must call player_play() to complete initialization
 *
 * EXAMPLE:
 *   Player player;
 *   extern const MusicData my_song;
 *   player_init(&player, &my_song, 0);
 *   // Now call player_play() every frame
 */
void player_init(Player* player, const MusicData* music, uint8_t song_num);

/**
 * Main playback routine - call once per frame.
 *
 * This is the heart of the player. It must be called at a fixed rate:
 * - PAL systems (Europe): 50 Hz (50 times per second)
 * - NTSC systems (US/Japan): 60 Hz (60 times per second)
 *
 * Typically, this is called from a raster interrupt (IRQ) or VBlank handler
 * to ensure precise timing.
 *
 * WHAT THIS FUNCTION DOES:
 * 1. Complete pending initialization (if init_song_num < 0)
 * 2. Execute global filter modulation
 * 3. For each channel (3 times):
 *    a. Update tick counter (timing)
 *    b. Fetch new notes when counter reaches zero
 *    c. Execute effects (portamento, vibrato, etc.)
 *    d. Execute wavetables (waveform/pitch changes)
 *    e. Execute pulse tables (PWM modulation)
 *    f. Execute sound effects (if active)
 *    g. Write final values to SID registers
 *
 * @param player Pointer to player state
 * @param music Pointer to music data
 *
 * TIMING REQUIREMENTS:
 * - MUST be called at exactly 50Hz (PAL) or 60Hz (NTSC)
 * - MUST complete within one frame (~20ms for PAL, ~16ms for NTSC)
 * - On C64 at 1MHz: should complete in < 20,000 cycles
 *
 * NOTES:
 * - This function modifies player state and writes to SID registers
 * - It does NOT modify the music data (music pointer is const)
 * - Safe to call from an interrupt handler (no blocking operations)
 * - If initialization is pending, this completes it before playback
 *
 * EXAMPLE INTERRUPT HANDLER:
 *   void __interrupt music_irq(void) {
 *       player_play(&player, &my_song);
 *       // Acknowledge interrupt
 *       VIC.raster_irq = 1;
 *   }
 */
void player_play(Player* player, const MusicData* music);

/**
 * Play a sound effect on a channel.
 *
 * Sound effects temporarily override normal music playback on the specified
 * channel. The SFX will play to completion, then normal music resumes.
 *
 * PRIORITY SYSTEM:
 * Sound effects use address-based priority. A SFX will only start if its
 * address is higher than any currently playing SFX on that channel. This
 * allows important sounds (like explosions) to override less important
 * sounds (like footsteps) when placed at higher addresses in memory.
 *
 * SOUND EFFECT FORMAT:
 * SFX data is a simple byte sequence:
 *   Byte 0: Attack/Decay value (ADSR envelope)
 *   Byte 1: Sustain/Release value (ADSR envelope)
 *   Byte 2: Pulse width (8-bit, same value for low and high bytes)
 *   Byte 3+: Note values ($80-$FF) or waveforms ($00-$81)
 *   End: $00 (terminator)
 *
 * Notes and waveforms can be interleaved:
 *   $85, $41    - Play note $85 with waveform $41
 *   $90         - Play note $90 (keep previous waveform)
 *   $00         - End of SFX
 *
 * @param player Pointer to player state
 * @param music Pointer to music data (needed for frequency table)
 * @param channel Channel number (0-2) to play SFX on
 * @param sfx_data Pointer to sound effect data (must remain valid until SFX completes)
 *
 * NOTES:
 * - The sfx_data pointer must remain valid while the SFX plays
 * - SFX data should be in ROM (const) for typical usage
 * - Channel 0 = voice 1, channel 1 = voice 2, channel 2 = voice 3
 * - SFX with higher addresses have higher priority
 * - When SFX completes, normal music playback resumes on that channel
 * - SFX playback is advanced by player_play() every frame
 *
 * EXAMPLE:
 *   // SFX data in ROM
 *   const uint8_t explosion_sfx[] = {
 *       0x09,       // Attack/Decay (fast attack, medium decay)
 *       0xF0,       // Sustain/Release (high sustain, fast release)
 *       0x80,       // Pulse width
 *       0xC0, 0x80, // Play note $C0 with noise waveform $80
 *       0xB0,       // Play note $B0 (pitch down)
 *       0xA0,       // Play note $A0 (pitch down more)
 *       0x00        // End of SFX
 *   };
 *
 *   player_play_sfx(&player, &my_song, 0, explosion_sfx);
 */
void player_play_sfx(Player* player, const MusicData* music,
                     uint8_t channel, const uint8_t* sfx_data);

/**
 * Set master volume.
 *
 * This function immediately updates the master volume, which affects all
 * voices simultaneously. Volume changes take effect on the next frame.
 *
 * The master volume is combined with the filter mode bits when written
 * to the SID, so this preserves any active filter settings.
 *
 * @param player Pointer to player state
 * @param volume Volume level (0-15, where 0=silence and 15=maximum)
 *
 * NOTES:
 * - Volume changes take effect immediately (on next player_play call)
 * - This function only updates player state, not SID registers directly
 * - The actual SID write happens in player_play()
 * - Volume above 15 is clamped to 15 (only lower 4 bits used)
 * - This does not affect individual voice volumes (use instruments for that)
 *
 * EXAMPLE:
 *   player_set_master_volume(&player, 15);  // Full volume
 *   player_set_master_volume(&player, 8);   // Half volume
 *   player_set_master_volume(&player, 0);   // Silence (mute)
 */
void player_set_master_volume(Player* player, uint8_t volume);

//=============================================================================
// UTILITY FUNCTIONS (Optional)
//=============================================================================

/**
 * Get current song position for a channel.
 *
 * Returns the current position in the order list for the specified channel.
 * Useful for synchronizing game events with music position.
 *
 * @param player Pointer to player state
 * @param channel Channel number (0-2)
 * @return Current order list position (0-255)
 *
 * EXAMPLE:
 *   uint8_t pos = player_get_song_position(&player, 0);
 *   if (pos == 16) {
 *       // Trigger boss battle at pattern 16!
 *   }
 */
static inline uint8_t player_get_song_position(const Player* player, uint8_t channel) {
    return player->channels[channel].song_ptr;
}

/**
 * Get current pattern number for a channel.
 *
 * Returns the pattern currently playing on the specified channel.
 * Useful for synchronization and debugging.
 *
 * @param player Pointer to player state
 * @param channel Channel number (0-2)
 * @return Current pattern number (0-255)
 */
static inline uint8_t player_get_pattern_number(const Player* player, uint8_t channel) {
    return player->channels[channel].pattern_num;
}

/**
 * Check if a sound effect is playing on a channel.
 *
 * Returns true if a sound effect is currently active on the channel,
 * false if normal music is playing.
 *
 * @param player Pointer to player state
 * @param channel Channel number (0-2)
 * @return true if SFX is playing, false if normal music
 */
static inline bool player_is_sfx_playing(const Player* player, uint8_t channel) {
    return (player->channels[channel].sfx_frame != 0);
}

/**
 * Stop all sound effects.
 *
 * Immediately stops all sound effects on all channels and returns to
 * normal music playback.
 *
 * @param player Pointer to player state
 */
static inline void player_stop_all_sfx(Player* player) {
    for (uint8_t i = 0; i < NUM_CHANNELS; i++) {
        player->channels[i].sfx_frame = 0;
        player->channels[i].sfx_data = NULL;
    }
}

#endif // PLAYER3_H
